# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - proj

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_6ae246e54173450698349d5b1460f1a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6d86817895604db49fcb8dade7957b59 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6ae246e54173450698349d5b1460f1a3 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'proj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_285c5096bda24a0aa778fec45cdf97d9 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6ae246e54173450698349d5b1460f1a3 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'